### ISSUE TITLE
Invalid composer.json

### ISSUE THREAD

**Issue by oliver-la** [littlebizzy/disable-attachment-pages#1]
Hi there,

There's a missing comma here:

https://github.com/littlebizzy/disable-attachment-pages/blob/master/composer.json#L11

**Comment by jessuppi** [comment]
Thanks @xama5 :)

Actually we've been aware of this issue on many of our repos for a while but since we have not completed the shift toward using the Master branch and proper Composer support yet, it has not been fixed on most repos yet. Hopefully asap. Thanks again ~

**Comment by jessuppi** [comment]
A few years later, but we are moving forward with cleaning up many of our free plugins on GitHub and will no longer be supporting Composer... we're taking a simpler approach using just Master branch and Releases.
